plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        yarn lerna version ${nextRelease.version} --yes
      publishCmd: |
        yarn lerna publish from-git
  - "@semantic-release/github"
